# Generated by Django 2.2 on 2019-05-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin_signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='data_joined',
        ),
    ]
