# Generated by Django 2.2 on 2019-05-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190501_0951'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('signin_signup', '0002_remove_customuser_data_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
