# Generated by Django 2.2 on 2019-05-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_lesson', '0007_auto_20190502_0900'),
        ('ttest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='modul',
        ),
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='course_lesson.Module'),
            preserve_default=False,
        ),
    ]
