# Generated by Django 2.2 on 2019-05-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttest', '0002_auto_20190502_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='module',
            new_name='modul',
        ),
    ]
