# Generated by Django 2.2 on 2019-05-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttest', '0003_auto_20190502_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='modul',
            new_name='module',
        ),
    ]
