# Generated by Django 2.2 on 2019-05-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttest', '0004_auto_20190502_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytest',
            old_name='modul',
            new_name='module',
        ),
    ]
