# Generated by Django 2.2 on 2019-05-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_lesson', '0002_auto_20190501_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='course_lesson.Lesson'),
        ),
    ]
