# Generated by Django 2.2 on 2019-05-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_lesson', '0005_auto_20190501_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='next_lesson_id',
            new_name='next_id',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='previous_lesson_id',
            new_name='previous_id',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='next_module_id',
            new_name='next_id',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='previous_module_id',
            new_name='previous_id',
        ),
    ]
