# Generated by Django 2.2 on 2019-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_lesson', '0007_auto_20190502_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo_link',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_lesson'),
        ),
    ]
