# Generated by Django 2.2 on 2019-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_lesson', '0010_auto_20190502_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_lesson/teachers'),
        ),
    ]
